# Site settings
name: Ace Eddleman
title: Ace Eddleman | Web Developer
email: ace@acecodes.net
description: > # this means to ignore newlines until "baseurl:"
  A dedicated professional web developer from Southern California who lives, breathes and eats code. Emphasis on Python with Django or Flask, but always looking to learn new tools.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://acecodes.net" # the base hostname & protocol for your site
twitter_username: ""
github_username:  acecodes

# Build settings
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
markdown: kramdown
permalink: pretty
highlighter: pygments

assets:
  debug: false
  js_compressor:  uglifier
  css_compressor: sass
  sources:
    - _assets/javascript
    - _assets/stylesheets
    - _vendors/stylesheets
    - _vendors/javascript